### ISSUE TITLE
Don't panic on "custom" CAT48/030 data

### ISSUE THREAD

**Issue by nineff** [wcampbell0x2a/asterix-rs#31]
Currently, if you try to parse a Cat48 message which contains a Data Item I048/030, (Warning/Error Conditions and Target Classification) with a code higher than 31, the library panics. 

This is unfortunate since the [Standard](https://www.eurocontrol.int/sites/default/files/2022-12/eurocontrol-cat048-pt4-ed131.pdf) defines the codes up to 36, reserves the space up to code 63 and specifically allows custom Codes between 64 and 127:
`Values 0-63 are allocated by the AMG, values 64 to 127 are
available for allocation by manufacturers and shall be described in
the corresponding ICD`

It would be great if the library wouldn't crash on those values and even better if you could extract them somehow for further processing.

**Comment by wcampbell0x2a** [comment]
@nineff  https://github.com/wcampbell0x2a/asterix-rs/pull/32 should fix this.

**Comment by nineff** [comment]
awesome, that was fast ;)
I think you made a typo for the custom codes, it should be `Manufacturer`, not `Manufacture`

**Comment by wcampbell0x2a** [comment]
Fix released in `0.4.0`
